#+INCLUDE: "../../prefix.org"

#+TITLE: mail学习 rfc2822                     

Message-ID: <e0feef57-e609-4e14-acb0-65212a39380b@shingroup.cn>
Date: Thu, 29 Feb 2024 10:26:32 +0800
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Subject: Re: [PATCH v2] perf/hx_arm_ni: Support uncore ARM NI-700 PMU
Content-Language: en-US
From: =?UTF-8?B?WWFuZyBKaWFsb25nIOadqOS9s+m+mQ==?= <jialong.yang@shingroup.cn>
To: Robin Murphy <robin.murphy@arm.com>, Will Deacon <will@kernel.org>,
 Mark Rutland <mark.rutland@arm.com>
Cc: shenghui.qu@shingroup.cn, linux-kernel@vger.kernel.org,
 linux-arm-kernel@lists.infradead.org
References: <20240131070821.11477-1-jialong.yang@shingroup.cn>
 <fe3e97c0-f641-48d6-9941-837e73ae3cfe@arm.com>
 <7C9733413A0F8F60+0214f04d-173d-4513-ac1e-681c2f2a8de4@shingroup.cn>
 <8daf740f-f16b-49af-8da9-7c7750092539@arm.com>
 <fb75eadf-c029-4da7-bda5-300b7d7f51c1@shingroup.cn>
In-Reply-To: <fb75eadf-c029-4da7-bda5-300b7d7f51c1@shingroup.cn>
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

 From d11d3c01978ef0fd8bfd125189c671c9bcc3c096 Mon Sep 17 00:00:00 2001
From: yjl00405 <jialong.yang@shingroup.cn>
Date: Thu, 29 Feb 2024 09:39:51 +0800
Subject: [PATCH] arm-ni:Some changes.

---
1. Some small mistakes.
2. Have not given 'NI_PMU unit->ns = true'. So no cycles event exists
    in arm_ni_0_cd_0/events.
------------------------------------------------------------------
    
* 3.6.1 The origination date field(rarely used)
* 3.6.2 Originator fields(from/sender(rarely used)/reply-to)
From: "JiaLong.Yang" <jialong.yang@shingroup.cn>
可逗号分隔，同时指定多个mailbox。如果多个，那必须存在sender指明唯一一个发送地址。
也就是这个邮件来个多个实体人，但发送者只能从一个人那里。
git版本默认没有sender，因此from必须一个。
from指明message的作者，写信息的人。
sender指明信息真正发送者，邮件代理人。
NOTICE: 如果作者和发送人是同一个，则sender域不能单独使用。
git send-email --from=<address>

Reply-To: "JiaLong.Yang" <jialong.yang@shingroup.cn>
from中的一员，指明信息应该是由谁回复。
* 3.6.3 Destination address fields(to/cc/bcc)
To: Robin Murphy <robin.murphy@arm.com>, Will Deacon <will@kernel.org>,
 Mark Rutland <mark.rutland@arm.com>
Cc: shenghui.qu@shingroup.cn, linux-kernel@vger.kernel.org,
 linux-arm-kernel@lists.infradead.org
地址都可多个。

to指明信息第一接收人。
cc信息第二接收人，信息内容可能不会直接传给他们。
bcc, blind carbon copy，类似cc，但目标人不会cc/to的目标人看到。挺复杂的，看文档。

* 3.6.4 Identification fields(message-id/in-reply-to/references)
Message-ID: <e0feef57-e609-4e14-acb0-65212a39380b@shingroup.cn>
References: <20240131070821.11477-1-jialong.yang@shingroup.cn>
 <fe3e97c0-f641-48d6-9941-837e73ae3cfe@arm.com>
 <7C9733413A0F8F60+0214f04d-173d-4513-ac1e-681c2f2a8de4@shingroup.cn>
 <8daf740f-f16b-49af-8da9-7c7750092539@arm.com>
 <fb75eadf-c029-4da7-bda5-300b7d7f51c1@shingroup.cn>
In-Reply-To: <fb75eadf-c029-4da7-bda5-300b7d7f51c1@shingroup.cn>
message-id有且只有一个，由生成message-id的host保证唯一性。机器可读，对人无意义。
in-reply-to/references当创建回复消息时使用。他们持有目标回复消息的message-id。
in-reply-to标识新消息要回复的目标消息, 只有一个目标。
references标识一个对话线程，线程中的信息有多个。
in-reply-to field may be used to identify the message(s) to which the new message
is a reply.
references field may be used to identify a thread of conversation.
The "references" field will contain the contents of the parent's "reference" field followed by the contents of the parent's "message-id".
Reference: parent's Reference + parent's Message-Id
如果没有parent's reference，但是有parent's in-reply-to:
Reference: parent's in-reply-to + parent's Message-Id

* 3.6.5 Informational field(subject/comments(rarely-used)/keywords(rarely-used))
Subject: Re: [PATCH v2] perf/hx_arm_ni: Support uncore ARM NI-700 PMU
只有人可读。
当在reply中使用时，主题可以以Re: 开头，就像上面那样。不可以多字母或少字母，会导致不可预见的顺序问题。
comments是包含附加信息。

* 3.6.6 resent fields(rarely-used)